name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # test & lint deps
          pip install pytest pytest-cov flake8

      - name: Run linter
        run: |
          flake8 zpttlink --max-line-length=100

      - name: Run tests with coverage
        run: |
          pytest -v \
            --cov=zpttlink \
            --cov-report=xml \
            --cov-report=term-missing

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: false
        env:
          # Only needed for private repos or if Codecov requires it.
          # Add in GitHub: Settings → Secrets and variables → Actions → New repository secret
          # Name: CODECOV_TOKEN, Value: <your token from codecov.io>
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

